
MEMORY_PRIMITIVES_MKFILES_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MEMORY_PRIMITIVES_DIR := $(abspath $(MEMORY_PRIMITIVES_MKFILES_DIR)/..)

MEMORY_PRIMITIVES := $(MEMORY_PRIMITIVES_DIR)
export MEMORY_PRIMITIVES


